build.gradle
src/main/java/com/saebyeok/saebyeok/config/SecurityConfig.java
src/main/java/com/saebyeok/saebyeok/controller/ArticleController.java
src/main/java/com/saebyeok/saebyeok/domain/Article.java
src/main/java/com/saebyeok/saebyeok/domain/ArticleRepository.java
src/main/java/com/saebyeok/saebyeok/domain/Member.java
src/main/java/com/saebyeok/saebyeok/dto/ArticleCreateRequest.java
src/main/java/com/saebyeok/saebyeok/dto/ArticleResponse.java
src/main/java/com/saebyeok/saebyeok/exception/ArticleNotFoundException.java
src/main/java/com/saebyeok/saebyeok/service/ArticleService.java
src/main/resources/application.properties
src/test/java/com/saebyeok/saebyeok/acceptance/ArticleAcceptanceTest.java
src/test/java/com/saebyeok/saebyeok/controller/ArticleControllerTest.java
src/test/java/com/saebyeok/saebyeok/domain/ArticleRepositoryTest.java
src/test/java/com/saebyeok/saebyeok/service/ArticleServiceTest.java
src/test/resources/data.sql

#35 간단한 글 작성 기능 구현하기

---

src/main/java/com/saebyeok/saebyeok/controller/RootController.java

#58 배포된 서버에서 페이지 이동후 새로고침 시 404 에러 문제 수정하기

---

src/frontend/src/views/Post.vue
src/frontend/vue.config.js
src/main/java/com/saebyeok/saebyeok/controller/ArticleController.java
src/main/java/com/saebyeok/saebyeok/controller/CommentController.java
src/main/java/com/saebyeok/saebyeok/domain/Article.java
src/main/resources/data.sql
src/test/java/com/saebyeok/saebyeok/acceptance/ArticleAcceptanceTest.java
src/test/java/com/saebyeok/saebyeok/acceptance/CommentAcceptanceTest.java
src/test/java/com/saebyeok/saebyeok/controller/ArticleControllerTest.java
src/test/java/com/saebyeok/saebyeok/controller/CommentControllerTest.java

#48 글쓰기 초기 화면 구성하기

---

src/frontend/src/components/BottomNavigation.vue
src/frontend/src/components/Card.vue
src/frontend/src/views/Post.vue
src/test/java/com/saebyeok/saebyeok/domain/ArticleRepositoryTest.java
src/test/java/com/saebyeok/saebyeok/domain/CommentRepositoryTest.java

resolves: #61 
- 피드 페이지에서 시간이 올바르지 표시되지 않는 오류 수정
- 글쓰기 페이지에서 글 작성 시 리다이렉트가 되지 않는 오류 수정
- repository에 대한 테스트 코드가 올바르게 수행되지 않는 문제 수정

#61 피드 / 글쓰기 페이지의 오류 수정

---

.gitignore
src/main/java/com/saebyeok/saebyeok/config/WebMvcConfig.java
src/main/java/com/saebyeok/saebyeok/controller/GlobalExceptionAdvice.java
src/main/java/com/saebyeok/saebyeok/interceptor/LogInterceptor.java
src/main/resources/logback-spring.xml

#55 로깅 설정하기

---

src/frontend/src/styles/variables.scss

#64 기본 폰트 교체하기

---

src/frontend/src/App.vue
src/frontend/src/components/BottomNavigation.vue
src/frontend/src/components/EmotionsHeader.vue
src/frontend/src/router/index.js
src/frontend/src/views/Emotions.vue

#66 글쓰기 전 감정 대분류 이모지 선택 화면 구성하기

---

build.gradle
src/main/java/com/saebyeok/saebyeok/controller/GlobalExceptionAdvice.java
src/main/java/com/saebyeok/saebyeok/controller/MemberController.java
src/main/java/com/saebyeok/saebyeok/dto/LoginRequest.java
src/main/java/com/saebyeok/saebyeok/dto/TokenResponse.java
src/main/java/com/saebyeok/saebyeok/exception/IllegalSocialLoginException.java
src/main/java/com/saebyeok/saebyeok/infra/JwtTokenProvider.java
src/main/java/com/saebyeok/saebyeok/service/MemberService.java
src/main/resources/application.properties
src/test/java/com/saebyeok/saebyeok/acceptance/MemberAcceptanceTest.java
src/test/java/com/saebyeok/saebyeok/controller/MemberControllerTest.java
src/test/java/com/saebyeok/saebyeok/infra/JwtTokenProviderTest.java
src/test/java/com/saebyeok/saebyeok/service/MemberServiceTest.java

#56 축소된 회원 가입 및 로그인 API 구현

---

src/frontend/src/views/diary/Diary.vue
src/frontend/src/views/diary/components/EmotionFilter.vue
src/frontend/src/views/emotions/components/EmotionButton.vue
src/frontend/src/views/post/Post.vue

resolved: #88
이 부분의 앞선 작업 #57 을 히로가 진행해주었는데,
그 과정에서 이미 컴포넌트 분리가 깔끔하게 되어있어 시간을 크게 단축했습니다.
실제 수행 과정 및 작업내역은 노션에 공유드립니다.
[링크](https://www.notion.so/Vue-c09b7d9eed574921a4892411a912a020)
이슈트래커 / [Vue] 다이어리 필터 구현 부분입니다.
일요일에는 부득이하게 작업이 어려울 듯 하고, 월요일에도 오전중에는 잠시 병원도 다녀오고 할까 싶어서요.
그런 만큼 오늘 미리 작업을 수행해 리뷰를 보내게 되었습니다.
부담가지지 마시고 월요일 내지 화요일까지만 리뷰해주시면 될 것 같습니다.
모두들 즐거운 주말 보내시기를 바랍니다.
다음주 화요일에 뵙겠습니다. 감사합니다.

#88 프론트엔드의 다이어리 필터 기능 구현하기

---

src/frontend/src/components/Comment.vue
src/frontend/src/components/card/Card.vue
src/frontend/src/components/card/DetailPageCard.vue

resolved #91 
프론트엔드 단 게시물과 댓글의 추천 기능입니다.
현재 추천 기능을 위한 백엔드 설계가 이루어지지 않은 상태입니다.
따라서 백엔드 연결을 위한 작업(뷰엑스 모듈 분리, api 등록 등)은 설계가 이루어진 후 반영할 예정입니다.

#91 프론트엔드의 게시물, 댓글 추천 기능 구현하기

---

src/main/java/com/saebyeok/saebyeok/config/SecurityConfig.java
src/main/java/com/saebyeok/saebyeok/security/CustomAuthenticationEntryPoint.java

#105 백엔드에서 에러 메시지를 json으로 보내기

---

src/frontend/src/components/card/Card.vue
src/frontend/src/components/card/DetailPageCard.vue

#136 카드에서 신고 버튼 제외하기

---

src/main/java/com/saebyeok/saebyeok/controller/AnalysisController.java
src/main/java/com/saebyeok/saebyeok/domain/CommentRepository.java
src/main/java/com/saebyeok/saebyeok/dto/CommentsAnalysisResponse.java
src/main/java/com/saebyeok/saebyeok/service/AnalysisService.java
src/main/java/com/saebyeok/saebyeok/service/CommentService.java
src/test/java/com/saebyeok/saebyeok/documentation/AnalysisDocumentation.java
src/test/java/com/saebyeok/saebyeok/domain/CommentRepositoryTest.java
src/test/java/com/saebyeok/saebyeok/service/AnalysisServiceTest.java

resolved #124 
article은 아직 삭제 상태가 없어서 우선 댓글만이라도 삭제하지 않은 댓글 기준으로 적용해 봤어요~
검토 부탁합니다 🙏🏻

#124 댓글 분석 API 추가하기와 분석 API 내부 로직 수정하기

---

src/frontend/src/components/card/Card.vue
src/frontend/src/components/card/DetailPageCard.vue
src/frontend/src/components/comment/Comment.vue

공감 버튼이 클릭되기 전에는 회색의 mdi-hand-heart-outline 아이콘,
클릭이 되면 mdi-hand-heart 아이콘에 보라색 색깔이 들어가도록 하였습니다!
resolves: #145

#145 프론트엔드 공감 버튼 리팩토링

---

src/frontend/package-lock.json
src/frontend/package.json
src/frontend/src/components/CreatedDate.vue

Resolved: #144 
사파리 브라우저에서 테스트 한 번 부탁드릴게요!!

#144 프론트엔드의 날짜 계산 리팩토링하기

---

src/frontend/src/components/comment/CommentCreateForm.vue
src/frontend/src/views/feed/Feed.vue
src/frontend/src/views/post/Post.vue

#143 프론트에서 사용자에게 휘발성을 알리고 작동을 알리는 요소 추가하기

---

src/frontend/src/components/EmotionFilter.vue
src/frontend/src/components/header/EmotionsHeader.vue
src/frontend/src/views/ErrorPage.vue
src/frontend/src/views/NotFoundPage.vue
src/frontend/src/views/analysis/Analysis.vue

#150 배경 색상 다듬기

---

src/frontend/package-lock.json
src/frontend/package.json
src/frontend/src/components/CreatedDate.vue
src/frontend/src/components/EmotionFilter.vue
src/frontend/src/components/FilterButton.vue
src/frontend/src/components/LogoutButton.vue
src/frontend/src/components/card/Card.vue
src/frontend/src/components/card/DetailPageCard.vue
src/frontend/src/components/comment/Comment.vue
src/frontend/src/components/comment/CommentCreateForm.vue
src/frontend/src/components/header/DetailPageHeader.vue
src/frontend/src/components/header/DiaryHeader.vue
src/frontend/src/components/header/EmotionsHeader.vue
src/frontend/src/components/header/Header.vue
src/frontend/src/router/index.js
src/frontend/src/views/ErrorPage.vue
src/frontend/src/views/NotFoundPage.vue
src/frontend/src/views/analysis/Analysis.vue
src/frontend/src/views/feed/Feed.vue
src/frontend/src/views/post/Post.vue

#149 프론트엔드 댓글 컴포넌트 구조 다듬기

---

src/frontend/package-lock.json
src/frontend/package.json
src/frontend/src/main.js

resolved #156 
으음..? 그냥 이렇게 하면 되나봅니다.. ㅎㅎ
머지돼야 제대로 작동하는지 볼 수 있을 것 같아요

#156 구글 애널리틱스(GA) 적용하기

---

src/frontend/src/components/card/DetailCardMenu.vue
src/frontend/src/components/comment/CommentMenu.vue

#161 댓글 삭제 기능이 모바일에서 종종 이루어지지 않는 버그 수정

---

src/main/java/com/saebyeok/saebyeok/config/WebMvcConfig.java
src/main/java/com/saebyeok/saebyeok/controller/AnalysisController.java
src/main/java/com/saebyeok/saebyeok/controller/ArticleController.java
src/main/java/com/saebyeok/saebyeok/controller/CommentController.java
src/main/java/com/saebyeok/saebyeok/controller/LikeController.java
src/main/java/com/saebyeok/saebyeok/controller/resolver/LoginMember.java
src/main/java/com/saebyeok/saebyeok/controller/resolver/LoginMemberArgumentResolver.java
src/main/java/com/saebyeok/saebyeok/domain/LoginMember.java
src/main/java/com/saebyeok/saebyeok/service/MemberService.java
src/test/java/com/saebyeok/saebyeok/controller/resolver/LoginMemberArgumentResolverTest.java
src/test/java/com/saebyeok/saebyeok/service/MemberServiceTest.java

#164 컨트롤러에서 인증된 유저를 구하는 코드 리팩토링하기

---

src/main/java/com/saebyeok/saebyeok/config/WebMvcConfig.java
src/main/java/com/saebyeok/saebyeok/controller/AnalysisController.java
src/main/java/com/saebyeok/saebyeok/controller/ArticleController.java
src/main/java/com/saebyeok/saebyeok/controller/CommentController.java
src/main/java/com/saebyeok/saebyeok/controller/LikeController.java
src/main/java/com/saebyeok/saebyeok/controller/resolver/LoginMember.java
src/main/java/com/saebyeok/saebyeok/controller/resolver/LoginMemberArgumentResolver.java
src/main/java/com/saebyeok/saebyeok/domain/LoginMember.java
src/main/java/com/saebyeok/saebyeok/exception/MemberNotFoundException.java
src/main/java/com/saebyeok/saebyeok/security/service/CustomOAuth2UserService.java
src/main/java/com/saebyeok/saebyeok/security/service/UserService.java
src/main/java/com/saebyeok/saebyeok/service/MemberService.java
src/test/java/com/saebyeok/saebyeok/controller/resolver/LoginMemberArgumentResolverTest.java
src/test/java/com/saebyeok/saebyeok/service/MemberServiceTest.java

#173 MemberService를 통해서만 Member 관련 DB 작업을 할 수 있도록 리팩토링하기

---

src/frontend/src/components/card/Card.vue

#180  게시물 본문에 들어간 줄바꿈이 적용되지 않는 이슈 해결하기

---

src/frontend/public/index.html
src/frontend/src/components/LogoutButton.vue
src/frontend/src/components/card/Card.vue
src/frontend/src/components/card/Cards.vue
src/frontend/src/components/comment/Comment.vue
src/frontend/src/components/comment/CommentCreateForm.vue
src/frontend/src/views/diary/Diary.vue
src/frontend/src/views/feed/Feed.vue

Resolved #208 
보시고 더 좋은 방법이나 제안도 주시면 감사하겠읍니다 🤗

#208 피드 & 기록, 게시글 상세 조회 페이지 개선하기

---

src/frontend/src/components/header/DetailPageHeader.vue
src/frontend/src/components/header/Header.vue

#210 비회원 사용자에게 로그아웃 버튼 숨기기

---

src/docs/asciidoc/api-docs.adoc
src/frontend/src/api/modules/article.js
src/frontend/src/api/modules/comment.js
src/frontend/src/components/comment/Comment.vue
src/frontend/src/store/modules/comment.js
src/main/java/com/saebyeok/saebyeok/controller/LikeController.java
src/test/java/com/saebyeok/saebyeok/acceptance/AcceptanceTest.java
src/test/java/com/saebyeok/saebyeok/acceptance/ArticleAcceptanceTest.java
src/test/java/com/saebyeok/saebyeok/acceptance/CommentAcceptanceTest.java
src/test/java/com/saebyeok/saebyeok/acceptance/LikeAcceptanceTest.java
src/test/java/com/saebyeok/saebyeok/controller/LikeControllerTest.java
src/test/java/com/saebyeok/saebyeok/documentation/LikeDocumentation.java

공감 요청 경로 수정했습니다.
추가로 인수테스트 @Disabled 되어 있던 이력으로 빠졌던 공감 인수테스트도 추가했습니다 :)
resolves: #215

#215 공감 요청 경로 수정하기

---

src/frontend/src/components/FilterButton.vue
src/frontend/src/components/LoginButton.vue
src/frontend/src/components/header/DetailPageHeader.vue
src/frontend/src/components/header/Header.vue

#214 로그인 버튼 만들기

---

src/main/java/com/saebyeok/saebyeok/controller/LikeController.java
src/main/java/com/saebyeok/saebyeok/domain/Comment.java
src/test/java/com/saebyeok/saebyeok/domain/CommentTest.java

이전에 사용하지 않아서 삭제한 코드인데, merge 과정에서 되살아났네요...!
다시 삭제할게요~
하면서 보니까 post 요청의 응답 loacation에 오류가 있어서 얘도 같이 수정했어요..!
resolves: #231

#231 사용하지 않는 코드 삭제 및 응답 Location 오류 수정

---

build.gradle
src/main/java/com/saebyeok/saebyeok/SaebyeokApplication.java
src/main/java/com/saebyeok/saebyeok/service/EmotionService.java
src/main/java/com/saebyeok/saebyeok/service/report/ReportService.java

Resolved #234 
라이브러리 덕에 생각보다 더 간단하게 완료했네용 🙃 이슈에 레퍼런스 기록해 두었습니다~
아 그리고 ReportService의 readReportCategory는 private 메서드라 캐싱 설정이 안된다고 하더라구요 🥺
이 메서드를 public으로 열고 캐싱한 값을 사용할지, 아니면 private으로 잠궈둘지도 고려해 볼만한 것 같아요.
이슈에도 올렸는데, 정말 캐싱되는 건가?? 해서 준비해본 적용 차이 캡쳐입니닷

#234 조회 메서드의 동일한 결과값 캐시하기
